[package]
name = "lsystem"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jzon = "0.12.5"
turtle-graphics = "*"
clap = { version = "4", features = ["derive"] }
